# Generated by Django 5.0.7 on 2024-07-18 07:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="red",
            name="description",
            field=ckeditor.fields.RichTextField(
                default="Descripción por defecto", verbose_name="Descripción"
            ),
            preserve_default=False,
        ),
    ]
